version: "2"

services:
    frontend:
        build: ./frontend/
        networks:
            - pnet
        volumes:
            - ./frontend/:/site/
        links:
            - backend:backend
        ports:
            - 4242:2015

    backend:
        build: ./backend/
        networks:
            - pnet
        volumes:
            - ./backend/:/go/src/github.com/guilhermebr/pirat.as/backend


networks:
    pnet:
        driver: bridge
