frontend:
    build: ./frontend/
    command: "go run /go/src/github.com/mholt/caddy/caddy/main.go"
    volumes:
        - ./frontend/:/site/
        - $GOPATH/src/github.com/mholt/caddy/:/go/src/github.com/mholt/caddy/
    links:
        - backend:backend
    ports:
        - 4242:2015

backend:
    build: ./backend/
    volumes:
        - ./backend/:/go/src/github.com/guilhermebr/pirat.as/backend

